### ISSUE TITLE
Package dependencies are not specified in setup.py

### ISSUE THREAD

**Issue by mikegerber** [NVlabs/ocrodeg#5]
[setup.py](https://github.com/NVlabs/ocrodeg/blob/master/setup.py) does not specify the package's dependencies, so that using it fails at first:

~~~
% virtualenv env
Using base prefix '/usr'
New python executable in /home/mike/devel/ocrodeg/env/bin/python3
Also creating executable in /home/mike/devel/ocrodeg/env/bin/python
Installing setuptools, pip, wheel...
done.
% . env/bin/activate
% pip install -e .
[... output omitted ...]
% python -c 'import ocrodeg'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mike/devel/ocrodeg/ocrodeg/__init__.py", line 2, in <module>
    from .degrade import *  # noqa
  File "/home/mike/devel/ocrodeg/ocrodeg/degrade.py", line 5, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
~~~

I'm submitting a PR to fix this.

**Comment by mikegerber** [comment]
PR #6
